### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by aurangakhtar** [AIAnytime/Search-Your-PDF-App#4]
Hello, 
I've encountered two issues. 

1. I had to specify a model manually (MBZUAI/LaMini-T5-738M). 

3. I received the following error message. 

(env) C:\AI\Search-Your-PDF-App>app.py
Traceback (most recent call last):
  File "C:\AI\Search-Your-PDF-App\app.py", line 16, in <module>
    base_model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint, device_map='auto', torch_dtype=torch.float32)
  File "C:\AI\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "C:\AI\env\lib\site-packages\transformers\modeling_utils.py", line 3307, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\AI\env\lib\site-packages\transformers\modeling_utils.py", line 3428, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.

What can I do? 

Thank you. 

Regards.

**Comment by Kedar-dave** [comment]
You can explicitly define device_map = "cpu" or "gpu" and retry. This worked for me
